# Generated by Django 5.2.4 on 2026-03-29 08:20

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Format: +[country code][number]', max_length=20, null=True, validators=[accounts.models.validate_phone_number])),
                ('sms_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('sms_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_verification_attempts', models.PositiveIntegerField(default=0)),
                ('sms_alert_threshold', models.PositiveIntegerField(default=30, help_text='Moisture level threshold for sending alerts (%)')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Start time for quiet hours (no alerts)')),
                ('quiet_hours_end', models.TimeField(default='06:00', help_text='End time for quiet hours (no alerts)')),
                ('sms_notification_frequency', models.IntegerField(choices=[(60, '1 Minute'), (120, '2 Minutes'), (180, '3 Minutes'), (240, '4 Minutes'), (300, '5 Minutes'), (360, '6 Minutes')], default=60, help_text='Frequency for SMS notifications in minutes')),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('last_sms_alert', models.DateTimeField(blank=True, null=True)),
                ('receive_sms_alerts', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['receive_sms_alerts', 'last_sms_alert'], name='accounts_cu_receive_51e455_idx'), models.Index(fields=['phone_number'], name='accounts_cu_phone_n_908ea4_idx'), models.Index(fields=['sms_verification_code', 'sms_verification_sent_at'], name='accounts_cu_sms_ver_f606a0_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
