# Generated by Django 5.2.4 on 2026-03-29 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_status', models.BooleanField(default=False)),
                ('manual_mode', models.BooleanField(default=False)),
                ('emergency', models.BooleanField(default=False)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('emergency_status', models.BooleanField(default=False)),
                ('operational_mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('pump_status', models.BooleanField(default=False)),
                ('moisture_threshold', models.IntegerField(default=50)),
                ('last_contact', models.DateTimeField(auto_now=True)),
                ('status_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Device Statuses',
                'ordering': ['-last_contact'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('water_used_liters', models.FloatField(default=0)),
                ('trigger_reason', models.CharField(choices=[('auto_low_moisture', 'Automatic - Low Moisture'), ('manual', 'Manual Control'), ('scheduled', 'Scheduled Irrigation'), ('emergency', 'Emergency Override')], default='auto_low_moisture', max_length=50)),
                ('moisture_before', models.IntegerField(blank=True, null=True)),
                ('moisture_after', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Irrigation Event',
                'verbose_name_plural': 'Irrigation Events',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationFrequencyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('period_days', models.IntegerField(default=7)),
                ('total_events', models.IntegerField(default=0)),
                ('avg_interval_hours', models.FloatField(blank=True, null=True)),
                ('min_interval_hours', models.FloatField(blank=True, null=True)),
                ('max_interval_hours', models.FloatField(blank=True, null=True)),
                ('avg_water_per_event', models.FloatField(default=0)),
                ('total_water_used', models.FloatField(default=0)),
                ('projected_weekly_water', models.FloatField(default=0)),
                ('projected_monthly_water', models.FloatField(default=0)),
                ('avg_moisture_drop_per_cycle', models.FloatField(blank=True, null=True)),
                ('estimated_dry_out_rate', models.FloatField(blank=True, help_text='% moisture loss per hour', null=True)),
                ('frequency_status', models.CharField(choices=[('low', 'Low Frequency'), ('normal', 'Normal Frequency'), ('high', 'High Frequency'), ('increasing', 'Increasing Trend'), ('decreasing', 'Decreasing Trend')], default='normal', max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('urgent_stock_alert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Irrigation Frequency Analysis',
                'verbose_name_plural': 'Irrigation Frequency Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.IntegerField(blank=True, null=True)),
                ('pump_status', models.BooleanField(default=False)),
                ('threshold', models.IntegerField(default=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_stop', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Threshold',
                'verbose_name_plural': 'Historical Thresholds',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, choices=[('banana', 'Banana'), ('maize', 'Maize'), ('beans', 'Beans'), ('coffee', 'Coffee'), ('cassava', 'Cassava'), ('rice', 'Rice'), ('tomato', 'Tomato'), ('potato', 'Potato'), ('sugarcane', 'Sugarcane'), ('vegetables', 'Vegetables')], max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('loamy', 'Loamy'), ('sandy', 'Sandy')], max_length=50, null=True)),
                ('soil_moisture_threshold', models.IntegerField(default=50, help_text='Optimal soil moisture threshold for the selected crop/soil (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='WaterStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('current_tank_level', models.FloatField(help_text='Current water level in liters')),
                ('estimated_days_remaining', models.FloatField()),
                ('estimated_irrigations_remaining', models.IntegerField()),
                ('avg_daily_usage', models.FloatField()),
                ('avg_irrigations_per_day', models.FloatField()),
                ('recommended_stock_date', models.DateField()),
                ('recommended_stock_amount', models.FloatField(help_text='Recommended water to stock in liters')),
                ('urgent_action_needed', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterTankLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_percentage', models.FloatField(help_text='Water level percentage (0-100%)')),
                ('volume', models.FloatField(help_text='Water volume in liters')),
                ('height', models.FloatField(blank=True, help_text='Water height in cm', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Tank Level',
                'verbose_name_plural': 'Water Tank Levels',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_used', models.FloatField(help_text='Volume of water used in liters')),
                ('initial_volume', models.FloatField(help_text='Initial water volume in liters')),
                ('final_volume', models.FloatField(help_text='Final water volume in liters')),
                ('measurement_period', models.DurationField(help_text='Time period over which usage was measured')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Usage',
                'verbose_name_plural': 'Water Usage Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
